server:
  port: 8091

spring:
  application:
    name: shop-product-${server.port}
  redis:
    host: 120.78.3.7
    port: 6379
    password: leis666
    #    sentinel:
    #      master: mymaster
    #      nodes: 120.78.3.7:26379
    database: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: shop-product-${server.port}
    prefer-ip-address: true
