server:
  port: 8080

spring:
  application:
    name: gateway-8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: gateway-8080
    prefer-ip-address: true

zuul:
  ignored-services:  "*"
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: shop-auth-8083
    user:
      paht: /user/**
      sensitiveHeaders:
      serviceId: shop-user-8090



#security:
#  oauth2:
#    client:
#      client-id: app
#      client-secret: 123456
#      access-token-uri: http://localhost:8083/oauth/token
#      grant-type: password
#
#    #     user-authorization-uri: http://localhost:8083/oauth/authorize
#    resource:
#      token-info-uri: http://localhost:8083/oauth/check_token
#      prefer-token-info: true
