server:
  port: 8090

spring:
  application:
    name: shop-user-8090
  redis:
    host: 120.78.3.7
    port: 6379
    password: leis666
      #    sentinel:
      #      master: mymaster
    #      nodes: 120.78.3.7:26379
    database: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: shop-user-8090
    prefer-ip-address: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8083/auth/member
      prefer-token-info: false