spring:
  application:
    name: shop-user-8090
  redis:
    host: 127.0.0.1
    port: 6379
    password: leis666
    database: 3
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8720
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            ruleType: flow

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: shop-user-8090
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: when_authorized

feign:
  sentinel:
    enabled: true

param: true
#
#feign:
#  hystrix:
#    enabled: true

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8083/auth/member
#    client:
#      client-id: app
#      client-secret: 123456
#      grant-type: password
#      access-token-uri: http://localhost:8083/oauth/token


