server:
  port: 8090

spring:
  application:
    name: shop-user-8090
  redis:
    host: 127.0.0.1
    port: 6379
    password: leis666
    database: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: shop-user-8090
    prefer-ip-address: true

#security:
#  oauth2:
#    resource:
##      user-info-uri: http://localhost:8083/auth/member
#      token-info-uri: http://localhost:8083/oauth/check_token
#      prefer-token-info: true
#    client:
#      access-token-uri: http://localhost:8083/oauth/token
#      client-id: app
#      client-secret: 123456

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8083/auth/member
#    client:
#      client-id: app
#      client-secret: 123456
#      grant-type: password
#      access-token-uri: http://localhost:8083/oauth/token


