server:
  port: 8081

spring:
  application:
    name: eureka-server-8081



eureka:
  instance:
    hostname: eureka-server-8081
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
  server:
    enable-self-preservation: false
